services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: "--httpPort=8080"

  selenium-hub:
    image: selenium/hub:3.141.59 # Используем проверенную версию
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
      - "5500:5500"

  chrome:
    image: selenium/node-chrome:3.141.59 # Используем проверенную версию
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub

  firefox:
    image: selenium/node-firefox:3.141.59 # Используем проверенную версию
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub

volumes:
  jenkins_home: